export const GET_CONTACTS_LIST = 'GET_CONTACTS_LIST';
export const GET_CONTACT_DETAILS = 'GET_CONTACT_DETAILS';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SET_CONTACT = 'SET_CONTACT';
export const SET_ERROR = 'SET_ERROR';
