export const GET_CONTACTS_LIST = 'GET_CONTACTS_LIST';
export const GET_CONTACT_DETAILS = 'GET_CONTACT_DETAILS';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';

export const GET_CONTACTS_LIST_ERROR = 'GET_CONTACTS_LIST_ERROR';
export const GET_CONTACT_DETAILS_ERROR = 'GET_CONTACT_DETAILS_ERROR';
export const CREATE_CONTACT_ERROR = 'CREATE_CONTACT_ERROR';
export const UPDATE_CONTACT_ERROR = 'UPDATE_CONTACT_ERROR';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';
